---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - >-
            --config-data={
              extends: default,
              rules: {
                anchors: enable,
                braces: {
                  forbid: non-empty
                },
                brackets: {
                  forbid: non-empty
                },
                colons: enable,
                commas: enable,
                comments: {
                  min-spaces-from-content: 1
                },
                comments-indentation: enable,
                document-end: disable,
                document-start: enable,
                empty-lines: enable,
                empty-values: disable,
                float-values: enable,
                hyphens: enable,
                indentation: enable,
                key-duplicates: enable,
                key-ordering: disable,
                line-length: {
                  max: 160
                },
                new-line-at-end-of-file: enable,
                new-lines: enable,
                octal-values: enable,
                quoted-strings: {
                  quote-type: double,
                  required: only-when-needed
                },
                trailing-spaces: enable,
                truthy: {
                  check-keys: false
                }
              }
            }
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args:
          - --exit-non-zero-on-fix
          - --fix
      - id: ruff-format
  - repo: https://github.com/crate-ci/typos
    rev: v1.36.2
    hooks:
      - id: typos
        args:
          - --force-exclude
          - --hidden
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.32
    hooks:
      - id: pymarkdown
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
        exclude: \.(tsv|xsd|xml)$
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
        args:
          - --all
          - --in-place
          - --spaces-indent-inline-array=4
          - --trailing-comma-inline-array
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        args:
          - --prose-wrap=always
          - --quote-props=as-needed
      - id: prettier
        name: prettier (xml)
        additional_dependencies:
          - prettier@2.8.8
          - "@prettier/plugin-xml@1.1.0"
        files: \.(xml|svg|xsd)$
        args:
          - --write
          - --xml-whitespace-sensitivity=ignore
      - id: prettier
        name: prettier (java)
        additional_dependencies:
          - prettier@2.8.8
          - prettier-plugin-java@2.0.0
        files: \.(java|vm|vsl)$
        args:
          - --write
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args:
          - --enforce-all
          - --maxkb=5000
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude: .j2$
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.34.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args:
          - --external-sources
          - --shell=bash
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
